#!/bin/bash
PREFIXPATH=${TOOLCHAIN_PREFIX}

mkdir -p build
cd build

cmake -D CMAKE_CXX_FLAGS="-g -O3 -fmax-errors=1" -DARITH="easy" -DBUILD_BLS_PYTHON_BINDINGS=0  -DBUILD_BLS_TESTS=0 -DBUILD_BLS_BENCHMARKS=0 \
-DPREFIXPATH=${PREFIXPATH} \
-DMINGW=1 \
-DCMAKE_SYSTEM_NAME=Windows \
-DCMAKE_SYSTEM_PROCESSOR=x86_64 \
-DCMAKE_INSTALL_PREFIX=${PREFIXPATH} \
-DCMAKE_PREFIX_PATH=${PREFIXPATH} \
-DCMAKE_FIND_ROOT_PATH=/opt/llvm-mingw/x86_64-w64-mingw32/include \
-DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
-DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY \
-DCMAKE_C_COMPILER=x86_64-w64-mingw32-gcc \
-DCMAKE_CXX_COMPILER=x86_64-w64-mingw32-g++ \
-DCMAKE_RC_COMPILER=x86_64-w64-mingw32-windres ..

make -j8
